--Question 1;
SELECT  DEPARTMENT_ID, LISTAGG (FIRST_NAME || ' ' || LAST_NAME || '; ') WITHIN GROUP (ORDER BY DEPARTMENT_ID) AS newList FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
--Question 2;
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY, SUM(SALARY) OVER (PARTITION BY JOB_ID ORDER BY EMPLOYEE_ID ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) NUM FROM EMPLOYEES;
--Question 3;
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, HIRE_DATE, DEPARTMENT_ID, PHONE_NUMBER, LEAD(PHONE_NUMBER,1) OVER (PARTITION BY DEPARTMENT_ID ORDER BY EMPLOYEE_ID) NEXT_VALUE  FROM EMPLOYEES ORDER BY HIRE_DATE;
--Question 4;
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, HIRE_DATE, SALARY, RANK() OVER (PARTITION BY SALARY ORDER BY HIRE_DATE) NUM FROM EMPLOYEES;
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, HIRE_DATE, SALARY, ROW_NUMBER() OVER (PARTITION BY SALARY ORDER BY HIRE_DATE) NUM FROM EMPLOYEES;
--Question 5;
SELECT EMPLOYEES.*, WIDTH_BUCKET(EMPLOYEE_ID,100,199,10) AS ORDERING FROM EMPLOYEES;
--Question 6;
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, SALARY, AVG_DEPT, DECODE(SIGN(SALARY-TABLE_A.AVG_DEPT+1), 1, 1, 0) value
FROM(SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID, AVG(SALARY) OVER (PARTITION BY DEPARTMENT_ID) AS AVG_DEPT, SALARY
    FROM EMPLOYEES
) TABLE_A
ORDER BY DEPARTMENT_ID; 
--Question 7;
SELECT *
FROM (SELECT EMP1.EMPLOYEE_ID, EMP1.FIRST_NAME, EMP1.LAST_NAME, EMP1.JOB_ID, EMP1.HIRE_DATE
, RANK() OVER (PARTITION BY (
                            SELECT NVL(SUBSTR(EMP2.HIRE_DATE, 8, INSTR(EMP2.HIRE_DATE, '-')-1), EMP2.HIRE_DATE)
                            FROM EMPLOYEES EMP2 
                            WHERE EMP2.EMPLOYEE_ID = EMP1.EMPLOYEE_ID                    
                )ORDER BY HIRE_DATE) RANKED
    FROM EMPLOYEES EMP1) VALUE_TABLE
WHERE VALUE_TABLE.RANKED = 1
ORDER BY VALUE_TABLE.HIRE_DATE;
--Question 8:
SELECT * 
FROM(SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY, FIRST_VALUE(salary) OVER (PARTITION BY department_id) FV 
    FROM employees emp) MY_TABLE
WHERE MY_TABLE.FV <> MY_TABLE.SALARY;
--Question 9:
SELECT * 
FROM(SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY, FIRST_VALUE(SALARY) OVER (PARTITION BY DEPARTMENT_ID) FV,
    MAX(SALARY) OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) FIRST_2_VAL
    FROM EMPLOYEES) MY_TABLE
WHERE MY_TABLE.FV=MY_TABLE.FIRST_2_VAL;
--Question 10;
SELECT * 
FROM(SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID, HIRE_DATE, FIRST_VALUE(HIRE_DATE) OVER (PARTITION BY DEPARTMENT_ID) FV,
    MIN(HIRE_DATE) OVER (PARTITION BY DEPARTMENT_ID ORDER BY HIRE_DATE ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) FIRST_2_VAL
    FROM EMPLOYEES) MY_TABLE
WHERE MY_TABLE.FV=MY_TABLE.FIRST_2_VAL;

